name: Deploy to AWS EC2 Windows VM with SCP.

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_REGION: us-east-1
      EC2_AMI_ID: ami-0455de3caedb4b2e0
      EC2_INSTANCE_TYPE: t3.medium
      EC2_KEY_NAME: my-key
      EC2_SECURITY_GROUP_ID: sg-0a8d78f4a99eeecfe

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.EC2_REGION }}

    - name: Base64-encode PowerShell script
      id: encode_script
      run: |
        base64 -w0 .github/scripts/enable-ssh.ps1 > script.b64
        echo "ENCODED_USERDATA=$(cat script.b64)" >> $GITHUB_ENV

    - name: Launch EC2 Windows instance with OpenSSH setup
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id $EC2_AMI_ID \
          --count 1 \
          --instance-type $EC2_INSTANCE_TYPE \
          --key-name $EC2_KEY_NAME \
          --security-group-ids $EC2_SECURITY_GROUP_ID \
          --user-data "$(cat script.b64)" \
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=CI-Deploy}]' \
          --query 'Instances[0].InstanceId' \
          --output text)

        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

    - name: Wait for instance to be running
      run: aws ec2 wait instance-running --instance-ids $INSTANCE_ID

    - name: Get public IP address
      run: |
        IP=$(aws ec2 describe-instances \
          --instance-ids $INSTANCE_ID \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)
        echo "EC2_PUBLIC_IP=$IP" >> $GITHUB_ENV

    - name: Create ZIP of repository
      run: zip -r project.zip . -x ".git/*"

    - name: Write private key to file
      run: |
        echo "${{ secrets.WINDOWS_KEY_PEM }}" > key.pem
        chmod 600 key.pem

    - name: Copy project files to EC2 via SCP
      run: |
        echo "Waiting for SSH port to become available..."
        for i in {1..3}; do
          nc -zv $EC2_PUBLIC_IP 22 && break || sleep 10
        done

        scp -o StrictHostKeyChecking=no -i key.pem project.zip Administrator@$EC2_PUBLIC_IP:/Users/Administrator/Documents/

    - name: Print manual unzip command
      run: |
        echo "✅ Подключись по RDP или SSH к $EC2_PUBLIC_IP"
        echo "📦 Распакуй архив:"
        echo "    Expand-Archive -Path C:\\Users\\Administrator\\Documents\\project.zip -DestinationPath C:\\Users\\Administrator\\Documents\\"
