# .github/workflows/deploy-to-ec2.yml

name: Deploy to AWS EC2 Windows VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Launch EC2 Windows instance
      id: ec2
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ami-0c9fb5d338f1eec43 \
          --count 1 \
          --instance-type t3.medium \
          --key-name my-key \
          --security-group-ids sg-0a8d78f4a99eeecfe \
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=CI-Deploy}]' \
          --query 'Instances[0].InstanceId' \
          --output text)
        
        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

    - name: Wait for EC2 to be running
      run: |
        aws ec2 wait instance-running --instance-ids $INSTANCE_ID

    - name: Get public IP
      id: get_ip
      run: |
        IP=$(aws ec2 describe-instances \
          --instance-ids $INSTANCE_ID \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)
        echo "EC2_PUBLIC_IP=$IP" >> $GITHUB_ENV

    - name: Zip repository
      run: zip -r project.zip . -x ".git/*"

    - name: Upload ZIP to temporary S3 bucket
      run: |
        BUCKET_NAME=ci-temp-bucket-${{ github.run_id }}
        aws s3 mb s3://$BUCKET_NAME || echo "Bucket exists"
        aws s3 cp project.zip s3://$BUCKET_NAME/
        echo "S3_BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

    - name: Wait for SSM to be available
      run: |
        echo "⏳ Wait for the instance to register in SSM..."
        for i in {1..30}; do
          STATUS=$(aws ssm describe-instance-information \
            --query "InstanceInformationList[?InstanceId=='$INSTANCE_ID'].PingStatus" \
            --output text)

          echo "SSM PingStatus: $STATUS"

          if [ "$STATUS" = "Online" ]; then
            echo "✅ Инстанс доступен через SSM."
            break
          fi
          sleep 10
        done

    - name: Copy and unzip files via SSM
      run: |
        aws ssm send-command \
          --instance-ids $INSTANCE_ID \
          --document-name "AWS-RunPowerShellScript" \
          --comment "Download and extract repo files" \
          --parameters commands="\
            aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/project.zip C:\\Users\\Administrator\\Documents\\project.zip; \
            Expand-Archive -Path C:\\Users\\Administrator\\Documents\\project.zip -DestinationPath C:\\Users\\Administrator\\Documents\\${{ env.BRANCH_NAME }}; \
            Remove-Item C:\\Users\\Administrator\\Documents\\project.zip" \
          --region ${{ env.AWS_REGION }}

    - name: Print access instructions
      run: |
        echo "✅ EC2 instance created: $INSTANCE_ID"
        echo "🖥 IP: $EC2_PUBLIC_IP"
        echo "📁 Files extracted to: C:\\Users\\Administrator\\Documents\\${{ env.BRANCH_NAME }}"
